server:
  port: 8080

# Hibernate JPA
spring:
  http:
    encoding: #解决浏览器中返回json显示乱码问题
      charset: utf-8
      enabled: true
      force: true
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    url: jdbc:mysql://119.29.94.246:3306/hbn_demo?characterEncoding=utf8
    username: dev
    password: dev
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      javax:
        persistence:
          validation:
            mode: auto
